PACKAGE_NAME = "ca_safe_band_mvp_c_line"
ENTRY_FILE = "ca_safe_band_mvp_c_line.py"
RUNTIME_MODE = "monitor_only_guidance"
BASIC_SCORING_REQUIRES_EXTERNAL_REFERENCE = False
PARQUET_RUNTIME_ENABLED = False
DCS_OUTPUT_ENABLED = False
HUMAN_REVIEW_REQUIRED_BEFORE_CONNECTION = True

DEFAULT_MIN_VALID_POINTS = 30
DEFAULT_TIME_COLUMN = "time"
DEFAULT_RESIDENCE_MINUTES_FOR_BACKFILL_VALIDATION = 174
