# Auto-generated embedded runtime assets for C-line IDB package.
# Do not edit by hand; regenerate from prepare_c_line_idb_final_pre_go_live_package.py.

SAFE_BAND_ARTIFACT = {'created_at': '2026-05-11T11:54:28',
 'artifact_version': '1.0.0',
 'product_positioning': 'stable_safe_band_mvp',
 'final_strategy': 'top_rule_only',
 'primary_dose_feature': 'ca_per_rubber_flow_win_60_mean',
 'calcium_feed_conversion_formula': 'recommended_ca_feed = recommended_ca_consumption * rubber_flow_2_win_60_mean when '
                                    'rubber_flow_2_win_60_mean is available',
 'source_artifact_path': 'models\\ca_interval_recommender_c_line\\rule_artifact.json',
 'accepted_rule_count': 21,
 'monitor_candidate_rule_count': 9,
 'final_rules': [{'rule_id': 'ca_regime_rule_001',
                  'regime_feature': 'bromine_feed_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0198672906756923,
                  'recommended_dose_max': 0.0202094367728631,
                  'recommended_dose_target': 0.0200383637242777,
                  'rule_grade': 'B',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9745762711864406,
                  'best_high_rate': 0.0084745762711864,
                  'best_low_rate': 0.0169491525423728,
                  'ok_lift_vs_overall': 0.1516712432534797,
                  'high_delta_vs_overall': -0.1362181611589812,
                  'low_delta_vs_overall': -0.0154530820944987,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': None},
                 {'rule_id': 'ca_regime_rule_004',
                  'regime_feature': 'rubber_flow_2_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0201194634931839,
                  'recommended_dose_max': 0.0204527205957236,
                  'recommended_dose_target': 0.020286092044453752,
                  'rule_grade': 'B',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9745762711864406,
                  'best_high_rate': 0.0169491525423728,
                  'best_low_rate': 0.0084745762711864,
                  'ok_lift_vs_overall': 0.1516712432534797,
                  'high_delta_vs_overall': -0.1277435848877947,
                  'low_delta_vs_overall': -0.0239276583656851,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': None},
                 {'rule_id': 'ca_regime_rule_007',
                  'regime_feature': 'neutral_alkali_feed_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0198675910908859,
                  'recommended_dose_max': 0.0202148222744097,
                  'recommended_dose_target': 0.0200412066826478,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 111,
                  'best_ok_rate': 0.963963963963964,
                  'best_high_rate': 0.009009009009009,
                  'best_low_rate': 0.027027027027027,
                  'ok_lift_vs_overall': 0.141058936031003,
                  'high_delta_vs_overall': -0.1356837284211585,
                  'low_delta_vs_overall': -0.0053752076098445,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_010',
                  'regime_feature': 'tank_rubber_conc_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0201347782160522,
                  'recommended_dose_max': 0.0204885480696429,
                  'recommended_dose_target': 0.02031166314284755,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 116,
                  'best_ok_rate': 0.9655172413793104,
                  'best_high_rate': 0.0344827586206896,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1426122134463494,
                  'high_delta_vs_overall': -0.1102099788094779,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_012',
                  'regime_feature': 'tank_rubber_conc_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0197621476389604,
                  'recommended_dose_max': 0.0205093950900982,
                  'recommended_dose_target': 0.0201357713645293,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.9316239316239316,
                  'best_high_rate': 0.0427350427350427,
                  'best_low_rate': 0.0256410256410256,
                  'ok_lift_vs_overall': 0.1087189036909707,
                  'high_delta_vs_overall': -0.1019576946951248,
                  'low_delta_vs_overall': -0.0067612089958459,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': None},
                 {'rule_id': 'ca_regime_rule_013',
                  'regime_feature': 'esbo_feed_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.015048047594216,
                  'recommended_dose_max': 0.0199665303756579,
                  'recommended_dose_target': 0.01750728898493695,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9745762711864406,
                  'best_high_rate': 0.0254237288135593,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1516712432534797,
                  'high_delta_vs_overall': -0.1192690086166082,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_016',
                  'regime_feature': 'r513_temp_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0198629929943009,
                  'recommended_dose_max': 0.0206321992444512,
                  'recommended_dose_target': 0.02024759611937605,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 115,
                  'best_ok_rate': 0.9739130434782608,
                  'best_high_rate': 0.017391304347826,
                  'best_low_rate': 0.008695652173913,
                  'ok_lift_vs_overall': 0.1510080155452998,
                  'high_delta_vs_overall': -0.1273014330823416,
                  'low_delta_vs_overall': -0.0237065824629585,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_017',
                  'regime_feature': 'r513_temp_win_60_mean',
                  'regime_bin': 'low',
                  'recommended_dose_min': 0.0197509590179045,
                  'recommended_dose_max': 0.0203442620943502,
                  'recommended_dose_target': 0.02004761055612735,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.905982905982906,
                  'best_high_rate': 0.0854700854700854,
                  'best_low_rate': 0.0085470085470085,
                  'ok_lift_vs_overall': 0.083077878049945,
                  'high_delta_vs_overall': -0.0592226519600821,
                  'low_delta_vs_overall': -0.023855226089863,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_018',
                  'regime_feature': 'r513_temp_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0202796546822744,
                  'recommended_dose_max': 0.0206599808168497,
                  'recommended_dose_target': 0.020469817749562053,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9661016949152542,
                  'best_high_rate': 0.0338983050847457,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1431966669822932,
                  'high_delta_vs_overall': -0.1107944323454218,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_019',
                  'regime_feature': 'r514_temp_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0198973677434662,
                  'recommended_dose_max': 0.0207787120628998,
                  'recommended_dose_target': 0.020338039903183003,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 101,
                  'best_ok_rate': 0.9801980198019802,
                  'best_high_rate': 0.0099009900990099,
                  'best_low_rate': 0.0099009900990099,
                  'ok_lift_vs_overall': 0.1572929918690192,
                  'high_delta_vs_overall': -0.1347917473311576,
                  'low_delta_vs_overall': -0.0225012445378616,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_020',
                  'regime_feature': 'r514_temp_win_60_mean',
                  'regime_bin': 'low',
                  'recommended_dose_min': 0.0195953251722463,
                  'recommended_dose_max': 0.0201268074709975,
                  'recommended_dose_target': 0.0198610663216219,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 100,
                  'best_ok_rate': 0.9,
                  'best_high_rate': 0.1,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.077094972067039,
                  'high_delta_vs_overall': -0.0446927374301675,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_021',
                  'regime_feature': 'r514_temp_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0200912463498368,
                  'recommended_dose_max': 0.0204019864387303,
                  'recommended_dose_target': 0.02024661639428355,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 102,
                  'best_ok_rate': 0.9411764705882352,
                  'best_high_rate': 0.0490196078431372,
                  'best_low_rate': 0.0098039215686274,
                  'ok_lift_vs_overall': 0.1182714426552742,
                  'high_delta_vs_overall': -0.0956731295870303,
                  'low_delta_vs_overall': -0.0225983130682441,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_022',
                  'regime_feature': 'r510a_temp_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0196635122508649,
                  'recommended_dose_max': 0.0202018555780472,
                  'recommended_dose_target': 0.019932683914456052,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9576271186440678,
                  'best_high_rate': 0.0423728813559322,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1347220907111068,
                  'high_delta_vs_overall': -0.1023198560742353,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_023',
                  'regime_feature': 'r510a_temp_win_60_mean',
                  'regime_bin': 'low',
                  'recommended_dose_min': 0.0202627980855022,
                  'recommended_dose_max': 0.021282580737,
                  'recommended_dose_target': 0.0207726894112511,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 116,
                  'best_ok_rate': 0.9396551724137931,
                  'best_high_rate': 0.043103448275862,
                  'best_low_rate': 0.0172413793103448,
                  'ok_lift_vs_overall': 0.1167501444808322,
                  'high_delta_vs_overall': -0.1015892891543055,
                  'low_delta_vs_overall': -0.0151608553265267,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_024',
                  'regime_feature': 'r510a_temp_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0201347782160522,
                  'recommended_dose_max': 0.0206864965251406,
                  'recommended_dose_target': 0.0204106373705964,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.9401709401709402,
                  'best_high_rate': 0.0598290598290598,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1172659122379792,
                  'high_delta_vs_overall': -0.0848636776011077,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_025',
                  'regime_feature': 'r511a_temp_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0197644144806634,
                  'recommended_dose_max': 0.0202498540551444,
                  'recommended_dose_target': 0.0200071342679039,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.9658119658119658,
                  'best_high_rate': 0.0256410256410256,
                  'best_low_rate': 0.0085470085470085,
                  'ok_lift_vs_overall': 0.1429069378790048,
                  'high_delta_vs_overall': -0.1190517117891419,
                  'low_delta_vs_overall': -0.023855226089863,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_026',
                  'regime_feature': 'r511a_temp_win_60_mean',
                  'regime_bin': 'low',
                  'recommended_dose_min': 0.0201470966500339,
                  'recommended_dose_max': 0.0208787922591856,
                  'recommended_dose_target': 0.02051294445460975,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 115,
                  'best_ok_rate': 0.9391304347826088,
                  'best_high_rate': 0.0521739130434782,
                  'best_low_rate': 0.008695652173913,
                  'ok_lift_vs_overall': 0.1162254068496478,
                  'high_delta_vs_overall': -0.0925188243866893,
                  'low_delta_vs_overall': -0.0237065824629585,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_027',
                  'regime_feature': 'r511a_temp_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0202086702433628,
                  'recommended_dose_max': 0.0208658873003689,
                  'recommended_dose_target': 0.020537278771865848,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.9316239316239316,
                  'best_high_rate': 0.0598290598290598,
                  'best_low_rate': 0.0085470085470085,
                  'ok_lift_vs_overall': 0.1087189036909707,
                  'high_delta_vs_overall': -0.0848636776011077,
                  'low_delta_vs_overall': -0.023855226089863,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'},
                 {'rule_id': 'ca_regime_rule_028',
                  'regime_feature': 'r512a_temp_win_60_mean',
                  'regime_bin': 'high',
                  'recommended_dose_min': 0.0198872755047615,
                  'recommended_dose_max': 0.0206971976312819,
                  'recommended_dose_target': 0.020292236568021697,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 115,
                  'best_ok_rate': 0.9739130434782608,
                  'best_high_rate': 0.017391304347826,
                  'best_low_rate': 0.008695652173913,
                  'ok_lift_vs_overall': 0.1510080155452998,
                  'high_delta_vs_overall': -0.1273014330823416,
                  'low_delta_vs_overall': -0.0237065824629585,
                  'high_dose_avoidance_candidate': False,
                  'time_stable': True,
                  'monitor_chain_candidate': True,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': '该工况下中等钙单耗区间历史合格率更高，是否符合工艺机理？'},
                 {'rule_id': 'ca_regime_rule_029',
                  'regime_feature': 'r512a_temp_win_60_mean',
                  'regime_bin': 'low',
                  'recommended_dose_min': 0.0198288764663609,
                  'recommended_dose_max': 0.0204530232501796,
                  'recommended_dose_target': 0.020140949858270252,
                  'rule_grade': 'B',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 117,
                  'best_ok_rate': 0.8632478632478633,
                  'best_high_rate': 0.1282051282051282,
                  'best_low_rate': 0.0085470085470085,
                  'ok_lift_vs_overall': 0.0403428353149023,
                  'high_delta_vs_overall': -0.0164876092250393,
                  'low_delta_vs_overall': -0.023855226089863,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': False,
                  'engineering_review_question': None},
                 {'rule_id': 'ca_regime_rule_030',
                  'regime_feature': 'r512a_temp_win_60_mean',
                  'regime_bin': 'mid',
                  'recommended_dose_min': 0.0202289727867283,
                  'recommended_dose_max': 0.0205910836820826,
                  'recommended_dose_target': 0.02041002823440545,
                  'rule_grade': 'A',
                  'rule_status': 'accept_for_manual_case_review',
                  'sample_count': 118,
                  'best_ok_rate': 0.9830508474576272,
                  'best_high_rate': 0.0169491525423728,
                  'best_low_rate': 0.0,
                  'ok_lift_vs_overall': 0.1601458195246662,
                  'high_delta_vs_overall': -0.1277435848877947,
                  'low_delta_vs_overall': -0.0324022346368715,
                  'high_dose_avoidance_candidate': True,
                  'time_stable': True,
                  'monitor_chain_candidate': False,
                  'manual_review_only': False,
                  'reject_or_refine': True,
                  'engineering_review_question': '该工况下最高钙单耗分箱高 T90 风险偏高，是否需要设为人工复核条件？'}],
 'regime_boundaries': {'method': 'train_like_tertiles',
                       'boundaries': {'bromine_feed_win_60_mean': {'q_low_mid': 382.56338166666666,
                                                                   'q_mid_high': 399.64728500000007},
                                      'esbo_feed_win_60_mean': {'q_low_mid': 127.25145333333333,
                                                                'q_mid_high': 132.80832388888888},
                                      'neutral_alkali_feed_win_60_mean': {'q_low_mid': 5741.179091111111,
                                                                          'q_mid_high': 6147.004308888889},
                                      'r510a_temp_win_60_mean': {'q_low_mid': 40.234320000000004,
                                                                 'q_mid_high': 40.55949166666667},
                                      'r511a_temp_win_60_mean': {'q_low_mid': 20.334516666666673,
                                                                 'q_mid_high': 20.48866222222222},
                                      'r512a_temp_win_60_mean': {'q_low_mid': 44.118151666666655,
                                                                 'q_mid_high': 45.95758166666668},
                                      'r513_temp_win_60_mean': {'q_low_mid': 45.07468666666667,
                                                                'q_mid_high': 46.881008888888886},
                                      'r514_temp_win_60_mean': {'q_low_mid': 45.24326444444445,
                                                                'q_mid_high': 47.53277333333333},
                                      'rubber_flow_2_win_60_mean': {'q_low_mid': 47270.931535,
                                                                    'q_mid_high': 49047.96755555555},
                                      'tank_rubber_conc_win_60_mean': {'q_low_mid': 17.007741666666668,
                                                                       'q_mid_high': 18.933936111111112}},
                       'note': 'Boundaries are fitted on first 80% time-ordered train_like samples only.'},
 'aggregation_policy': {'strategy': 'top_rule_only',
                        'description': 'Use top_rule_only because the latest aggregation strategy test selected it for '
                                       'this finalized monitor-only artifact.'},
 'action_visibility_policy': {'inside_band': {'final_action_hint': 'hold_in_band',
                                              'action_visibility': 'monitor_only',
                                              'explanation_cn': '当前钙单耗处于推荐安全区间内，建议维持观察。'},
                              'above_band': {'final_action_hint': 'above_band_manual_review',
                                             'action_visibility': 'manual_review_required',
                                             'explanation_cn': '当前钙单耗高于推荐安全区间，历史数据中高 T90 风险偏高，建议人工复核是否需要小幅降钙。'},
                              'below_band': {'final_action_hint': 'below_band_diagnostic_only',
                                             'action_visibility': 'diagnostic_only',
                                             'explanation_cn': '当前钙单耗低于推荐安全区间，仅作诊断展示；当前 MVP 不给出加钙操作建议。'},
                              'missing': {'final_action_hint': 'no_recommendation_missing_input',
                                          'action_visibility': 'no_recommendation',
                                          'explanation_cn': '关键输入缺失，无法生成推荐区间。'}},
 'required_input_features': ['current_ca_consumption',
                             'recommended_ca_consumption_min',
                             'recommended_ca_consumption_max'],
 'optional_input_features': ['recommended_ca_consumption_target',
                             'confidence_level',
                             'matched_rule_ids',
                             'selected_rule_ids',
                             'rubber_flow_2_win_60_mean',
                             'ir_lag_context_value'],
 'output_schema': ['recommended_ca_consumption_min',
                   'recommended_ca_consumption_max',
                   'recommended_ca_consumption_target',
                   'interval_position',
                   'final_action_hint',
                   'action_visibility',
                   'explanation_cn',
                   'warning_flags'],
 'validation_summary': {'band_accuracy': 0.711484593837535,
                        'direction_accuracy': 0.8067226890756303,
                        'target_accuracy_5pct': 0.711484593837535,
                        'recommendation_coverage': 0.9972067039106145,
                        'final_strategy': 'top_rule_only',
                        'product_positioning': 'stable_safe_band_mvp',
                        'inside_band_ok_rate': 0.95,
                        'inside_band_high_rate': 0.05,
                        'inside_band_low_rate': 0.0,
                        'above_band_high_rate': 0.3419354838709677,
                        'below_band_low_rate': 0.0},
 'known_limitations': ['Offline validation only.',
                       'No causal proof.',
                       'No guarantee that T90 will be qualified when calcium consumption is inside the band.',
                       'Engineering human review is required before any monitor-chain use.'],
 'safety_constraints': {'monitor_only': True,
                        'automatic_control': False,
                        'dcs_writeback': False,
                        'increase_hint_hidden': True,
                        'engineering_review_required': True,
                        'no_guarantee_t90_qualified': True,
                        'shadow_trial_recommended': False},
 'warnings': ['Filtered strategy replay from 7160 rows to 1790 rows for strategy=top_rule_only.'],
 'assumptions': ['The final MVP locks top_rule_only from the latest aggregation strategy comparison.',
                 'Below-band conditions are diagnostic-only; no operational increase hint is exposed.',
                 'Above-band conditions require manual engineering review and are not automatic decrease commands.']}

SCHEMA = {'package_name': 'ca_safe_band_mvp',
 'package_version': '1.0.1',
 'artifact_version': '1.0.0',
 'created_at': '2026-05-11T11:55:06',
 'python_compatibility': 'Python >= 3.8; package.py avoids PEP 604 union syntax.',
 'required_features': ['ca_per_rubber_flow_win_60_mean',
                       'bromine_feed_win_60_mean',
                       'esbo_feed_win_60_mean',
                       'neutral_alkali_feed_win_60_mean',
                       'r510a_temp_win_60_mean',
                       'r511a_temp_win_60_mean',
                       'r512a_temp_win_60_mean',
                       'r513_temp_win_60_mean',
                       'r514_temp_win_60_mean',
                       'tank_rubber_conc_win_60_mean'],
 'optional_features': ['output_ir_corrected_offset_20_win_15_std',
                       'recommended_ca_consumption_max',
                       'recommended_ca_consumption_min',
                       'recommended_ca_consumption_target',
                       'rubber_flow_2_win_60_mean'],
 'output_schema': ['recommendation_status',
                   'current_ca_consumption',
                   'recommended_ca_consumption_min',
                   'recommended_ca_consumption_max',
                   'recommended_ca_consumption_target',
                   'recommended_ca_feed_min',
                   'recommended_ca_feed_max',
                   'recommended_ca_feed_target',
                   'interval_position',
                   'action_hint',
                   'action_visibility',
                   'confidence_level',
                   'matched_rule_count',
                   'matched_rule_ids',
                   'selected_rule_ids',
                   'rule_evidence_ok_rate',
                   'rule_evidence_high_rate',
                   'rule_evidence_low_rate',
                   'rule_evidence_sample_count',
                   'engineering_review_required',
                   'explanation_cn',
                   'warning_flags',
                   'input_valid',
                   'missing_required_features',
                   'model_version',
                   'artifact_version'],
 'action_visibility_policy': {'inside_band': {'final_action_hint': 'hold_in_band',
                                              'action_visibility': 'monitor_only',
                                              'explanation_cn': '当前钙单耗处于推荐安全区间内，建议维持观察。'},
                              'above_band': {'final_action_hint': 'above_band_manual_review',
                                             'action_visibility': 'manual_review_required',
                                             'explanation_cn': '当前钙单耗高于推荐安全区间，历史数据中高 T90 风险偏高，建议人工复核是否需要小幅降钙。'},
                              'below_band': {'final_action_hint': 'below_band_diagnostic_only',
                                             'action_visibility': 'diagnostic_only',
                                             'explanation_cn': '当前钙单耗低于推荐安全区间，仅作诊断展示；当前 MVP 不给出加钙操作建议。'},
                              'missing': {'final_action_hint': 'no_recommendation_missing_input',
                                          'action_visibility': 'no_recommendation',
                                          'explanation_cn': '关键输入缺失，无法生成推荐区间。'}},
 'safety_constraints': {'monitor_only': True,
                        'automatic_control': False,
                        'dcs_writeback': False,
                        'increase_hint_hidden': True,
                        'engineering_review_required': True,
                        'no_guarantee_t90_qualified': True,
                        'shadow_trial_recommended': False},
 'dependency_policy': {'package_py_standard_library_only_expected': True,
                       'third_party_dependencies_must_exist_in_IDB_requirements': True,
                       'no_serialized_model': True},
 'runtime_modes': {'production': 'Default. Ignores input matched_rule_ids and selected_rule_ids; matches rules from '
                                 'current feature values and q33/q66 boundaries.',
                   'replay': 'For equivalence testing only. May use matched_rule_ids/selected_rule_ids from historical '
                             'replay rows.'},
 'runtime_input_modes': ['engineered_feature_state', 'raw_platform_dataframe'],
 'feature_window_definitions': {'process_context_window_minutes': 60,
                                'ca_consumption_window_minutes': 60,
                                'ir_lag_offset_minutes': 20,
                                'ir_lag_window_minutes': 15,
                                'online_runtime_note': 'Online runtime uses trailing windows ending at current time, '
                                                       'not an additional 165min historical shift.'},
 'raw_point_mapping': {'rubber_flow_2': {'friendly': 'rubber_flow_2',
                                         'tag': 'B4-FIC-C51001.PV.F_CV',
                                         'output': 'rubber_flow_2_win_60_mean'},
                       'bromine_feed': {'friendly': 'bromine_feed',
                                        'tag': 'B4-FIC-C51004.PV.CV',
                                        'output': 'bromine_feed_win_60_mean'},
                       'tank_rubber_conc': {'friendly': 'tank_rubber_conc',
                                            'tag': 'B4-AT-C50002A-BIIR.PV.CV',
                                            'output': 'tank_rubber_conc_win_60_mean'},
                       'r510a_temp': {'friendly': 'r510a_temp',
                                      'tag': 'B4-TI-C51007A_S.PV.CV',
                                      'output': 'r510a_temp_win_60_mean'},
                       'r511a_temp': {'friendly': 'r511a_temp',
                                      'tag': 'B4-TI-C51101A_S.PV.CV',
                                      'output': 'r511a_temp_win_60_mean'},
                       'r512a_temp': {'friendly': 'r512a_temp',
                                      'tag': 'B4-TI-C51702A.PV.F_CV',
                                      'output': 'r512a_temp_win_60_mean'},
                       'ca_feed': {'friendly': 'ca_feed',
                                   'tag': 'B4-FIC-C51401.PV.F_CV',
                                   'output': 'ca_per_rubber_flow_win_60_mean'},
                       'esbo_feed': {'friendly': 'esbo_feed',
                                     'tag': 'B4-FIC-C51801.PV.F_CV',
                                     'output': 'esbo_feed_win_60_mean'},
                       'neutral_alkali_feed': {'friendly': 'neutral_alkali_feed',
                                               'tag': 'B4-FIC-C51605.PV.F_CV',
                                               'output': 'neutral_alkali_feed_win_60_mean'},
                       'r513_temp': {'friendly': 'r513_temp',
                                     'tag': 'B4-TI-C51301_S.PV.CV',
                                     'output': 'r513_temp_win_60_mean'},
                       'r514_temp': {'friendly': 'r514_temp',
                                     'tag': 'B4-TI-C51401_S.PV.CV',
                                     'output': 'r514_temp_win_60_mean'}}}

SUPPORT = {'created_at': '2026-05-11T11:54:51',
 'features': {'output_ir_corrected_offset_20_win_15_std': {'feature_role': 'diagnostic',
                                                           'required': False,
                                                           'source': 'runtime_state',
                                                           'lower_bound': None,
                                                           'upper_bound': None,
                                                           'median': None,
                                                           'q33': None,
                                                           'q66': None,
                                                           'unit': '',
                                                           'description': 'Optional outlet IR-lag volatility '
                                                                          'diagnostic; not an action trigger.'},
              'recommended_ca_consumption_max': {'feature_role': 'output_only',
                                                 'required': False,
                                                 'source': 'runtime_output',
                                                 'lower_bound': None,
                                                 'upper_bound': None,
                                                 'median': None,
                                                 'q33': None,
                                                 'q66': None,
                                                 'unit': 'ratio',
                                                 'description': 'Safe-band output field.'},
              'recommended_ca_consumption_min': {'feature_role': 'output_only',
                                                 'required': False,
                                                 'source': 'runtime_output',
                                                 'lower_bound': None,
                                                 'upper_bound': None,
                                                 'median': None,
                                                 'q33': None,
                                                 'q66': None,
                                                 'unit': 'ratio',
                                                 'description': 'Safe-band output field.'},
              'recommended_ca_consumption_target': {'feature_role': 'output_only',
                                                    'required': False,
                                                    'source': 'runtime_output',
                                                    'lower_bound': None,
                                                    'upper_bound': None,
                                                    'median': None,
                                                    'q33': None,
                                                    'q66': None,
                                                    'unit': 'ratio',
                                                    'description': 'Safe-band output field.'},
              'ca_per_rubber_flow_win_60_mean': {'feature_role': 'primary_dose_feature',
                                                 'required': True,
                                                 'source': 'runtime_state',
                                                 'lower_bound': None,
                                                 'upper_bound': None,
                                                 'median': None,
                                                 'q33': None,
                                                 'q66': None,
                                                 'unit': 'ratio',
                                                 'description': 'Normalized calcium consumption used to classify '
                                                                'current position.'},
              'bromine_feed_win_60_mean': {'feature_role': 'regime_feature',
                                           'required': True,
                                           'source': 'runtime_state',
                                           'lower_bound': None,
                                           'upper_bound': None,
                                           'median': None,
                                           'q33': 382.56338166666666,
                                           'q66': 399.64728500000007,
                                           'unit': '',
                                           'description': 'Regime matching feature from train-like tertile '
                                                          'boundaries.'},
              'esbo_feed_win_60_mean': {'feature_role': 'regime_feature',
                                        'required': True,
                                        'source': 'runtime_state',
                                        'lower_bound': None,
                                        'upper_bound': None,
                                        'median': None,
                                        'q33': 127.25145333333333,
                                        'q66': 132.80832388888888,
                                        'unit': '',
                                        'description': 'Regime matching feature from train-like tertile boundaries.'},
              'neutral_alkali_feed_win_60_mean': {'feature_role': 'regime_feature',
                                                  'required': True,
                                                  'source': 'runtime_state',
                                                  'lower_bound': None,
                                                  'upper_bound': None,
                                                  'median': None,
                                                  'q33': 5741.179091111111,
                                                  'q66': 6147.004308888889,
                                                  'unit': '',
                                                  'description': 'Regime matching feature from train-like tertile '
                                                                 'boundaries.'},
              'r510a_temp_win_60_mean': {'feature_role': 'regime_feature',
                                         'required': True,
                                         'source': 'runtime_state',
                                         'lower_bound': None,
                                         'upper_bound': None,
                                         'median': None,
                                         'q33': 40.234320000000004,
                                         'q66': 40.55949166666667,
                                         'unit': '',
                                         'description': 'Regime matching feature from train-like tertile boundaries.'},
              'r511a_temp_win_60_mean': {'feature_role': 'regime_feature',
                                         'required': True,
                                         'source': 'runtime_state',
                                         'lower_bound': None,
                                         'upper_bound': None,
                                         'median': None,
                                         'q33': 20.334516666666673,
                                         'q66': 20.48866222222222,
                                         'unit': '',
                                         'description': 'Regime matching feature from train-like tertile boundaries.'},
              'r512a_temp_win_60_mean': {'feature_role': 'regime_feature',
                                         'required': True,
                                         'source': 'runtime_state',
                                         'lower_bound': None,
                                         'upper_bound': None,
                                         'median': None,
                                         'q33': 44.118151666666655,
                                         'q66': 45.95758166666668,
                                         'unit': '',
                                         'description': 'Regime matching feature from train-like tertile boundaries.'},
              'r513_temp_win_60_mean': {'feature_role': 'regime_feature',
                                        'required': True,
                                        'source': 'runtime_state',
                                        'lower_bound': None,
                                        'upper_bound': None,
                                        'median': None,
                                        'q33': 45.07468666666667,
                                        'q66': 46.881008888888886,
                                        'unit': '',
                                        'description': 'Regime matching feature from train-like tertile boundaries.'},
              'r514_temp_win_60_mean': {'feature_role': 'regime_feature',
                                        'required': True,
                                        'source': 'runtime_state',
                                        'lower_bound': None,
                                        'upper_bound': None,
                                        'median': None,
                                        'q33': 45.24326444444445,
                                        'q66': 47.53277333333333,
                                        'unit': '',
                                        'description': 'Regime matching feature from train-like tertile boundaries.'},
              'rubber_flow_2_win_60_mean': {'feature_role': 'feed_conversion_feature',
                                            'required': False,
                                            'source': 'runtime_state',
                                            'lower_bound': None,
                                            'upper_bound': None,
                                            'median': None,
                                            'q33': 47270.931535,
                                            'q66': 49047.96755555555,
                                            'unit': '',
                                            'description': 'Regime matching feature from train-like tertile '
                                                           'boundaries.'},
              'tank_rubber_conc_win_60_mean': {'feature_role': 'regime_feature',
                                               'required': True,
                                               'source': 'runtime_state',
                                               'lower_bound': None,
                                               'upper_bound': None,
                                               'median': None,
                                               'q33': 17.007741666666668,
                                               'q66': 18.933936111111112,
                                               'unit': '',
                                               'description': 'Regime matching feature from train-like tertile '
                                                              'boundaries.'}},
 'raw_point_mapping': {'rubber_flow_2': {'friendly': 'rubber_flow_2',
                                         'tag': 'B4-FIC-C51001.PV.F_CV',
                                         'output': 'rubber_flow_2_win_60_mean'},
                       'bromine_feed': {'friendly': 'bromine_feed',
                                        'tag': 'B4-FIC-C51004.PV.CV',
                                        'output': 'bromine_feed_win_60_mean'},
                       'tank_rubber_conc': {'friendly': 'tank_rubber_conc',
                                            'tag': 'B4-AT-C50002A-BIIR.PV.CV',
                                            'output': 'tank_rubber_conc_win_60_mean'},
                       'r510a_temp': {'friendly': 'r510a_temp',
                                      'tag': 'B4-TI-C51007A_S.PV.CV',
                                      'output': 'r510a_temp_win_60_mean'},
                       'r511a_temp': {'friendly': 'r511a_temp',
                                      'tag': 'B4-TI-C51101A_S.PV.CV',
                                      'output': 'r511a_temp_win_60_mean'},
                       'r512a_temp': {'friendly': 'r512a_temp',
                                      'tag': 'B4-TI-C51702A.PV.F_CV',
                                      'output': 'r512a_temp_win_60_mean'},
                       'ca_feed': {'friendly': 'ca_feed',
                                   'tag': 'B4-FIC-C51401.PV.F_CV',
                                   'output': 'ca_per_rubber_flow_win_60_mean'},
                       'esbo_feed': {'friendly': 'esbo_feed',
                                     'tag': 'B4-FIC-C51801.PV.F_CV',
                                     'output': 'esbo_feed_win_60_mean'},
                       'neutral_alkali_feed': {'friendly': 'neutral_alkali_feed',
                                               'tag': 'B4-FIC-C51605.PV.F_CV',
                                               'output': 'neutral_alkali_feed_win_60_mean'},
                       'r513_temp': {'friendly': 'r513_temp',
                                     'tag': 'B4-TI-C51301_S.PV.CV',
                                     'output': 'r513_temp_win_60_mean'},
                       'r514_temp': {'friendly': 'r514_temp',
                                     'tag': 'B4-TI-C51401_S.PV.CV',
                                     'output': 'r514_temp_win_60_mean'}},
 'feature_window_definitions': {'process_context_window_minutes': 60,
                                'ca_consumption_window_minutes': 60,
                                'ir_lag_offset_minutes': 20,
                                'ir_lag_window_minutes': 15,
                                'online_runtime_note': 'Online runtime uses trailing windows ending at current time, '
                                                       'not an additional 165min historical shift.'},
 'point_bounds': [{'friendly_name': 'rubber_flow_2',
                   'dcs_tag': 'B4-FIC-C51001.PV.F_CV',
                   'runtime_feature': 'rubber_flow_2_win_60_mean',
                   'variable_name': '卤化工段胶液总量2',
                   'lower_bound': 30000.0,
                   'upper_bound': 65000.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'bromine_feed',
                   'dcs_tag': 'B4-FIC-C51004.PV.CV',
                   'runtime_feature': 'bromine_feed_win_60_mean',
                   'variable_name': '反应溴添加量',
                   'lower_bound': 200.0,
                   'upper_bound': 500.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'tank_rubber_conc',
                   'dcs_tag': 'B4-AT-C50002A-BIIR.PV.CV',
                   'runtime_feature': 'tank_rubber_conc_win_60_mean',
                   'variable_name': '储罐胶浓在线检测',
                   'lower_bound': 13.0,
                   'upper_bound': 25.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'r510a_temp',
                   'dcs_tag': 'B4-TI-C51007A_S.PV.CV',
                   'runtime_feature': 'r510a_temp_win_60_mean',
                   'variable_name': 'R510A温度',
                   'lower_bound': 38.0,
                   'upper_bound': 46.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'r511a_temp',
                   'dcs_tag': 'B4-TI-C51101A_S.PV.CV',
                   'runtime_feature': 'r511a_temp_win_60_mean',
                   'variable_name': 'R511A温度',
                   'lower_bound': 19.0,
                   'upper_bound': 25.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'r512a_temp',
                   'dcs_tag': 'B4-TI-C51702A.PV.F_CV',
                   'runtime_feature': 'r512a_temp_win_60_mean',
                   'variable_name': 'R512A温度',
                   'lower_bound': 39.0,
                   'upper_bound': 54.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'ca_feed',
                   'dcs_tag': 'B4-FIC-C51401.PV.F_CV',
                   'runtime_feature': 'ca_feed',
                   'variable_name': '硬脂酸钙加注量',
                   'lower_bound': 700.0,
                   'upper_bound': 1300.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'esbo_feed',
                   'dcs_tag': 'B4-FIC-C51801.PV.F_CV',
                   'runtime_feature': 'esbo_feed_win_60_mean',
                   'variable_name': 'ESBO加注量',
                   'lower_bound': 100.0,
                   'upper_bound': 170.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'neutral_alkali_feed',
                   'dcs_tag': 'B4-FIC-C51605.PV.F_CV',
                   'runtime_feature': 'neutral_alkali_feed_win_60_mean',
                   'variable_name': '中和碱液添加量',
                   'lower_bound': 2700.0,
                   'upper_bound': 7000.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'r513_temp',
                   'dcs_tag': 'B4-TI-C51301_S.PV.CV',
                   'runtime_feature': 'r513_temp_win_60_mean',
                   'variable_name': 'R513温度',
                   'lower_bound': 40.0,
                   'upper_bound': 55.0,
                   'unit': None,
                   'bound_found': True},
                  {'friendly_name': 'r514_temp',
                   'dcs_tag': 'B4-TI-C51401_S.PV.CV',
                   'runtime_feature': 'r514_temp_win_60_mean',
                   'variable_name': 'R514温度',
                   'lower_bound': 40.0,
                   'upper_bound': 55.0,
                   'unit': None,
                   'bound_found': True}]}

MODEL_METADATA = {'package_name': 'ca_safe_band_mvp_c_line',
 'generated_at': '2026-05-13T19:02:03',
 'runtime_mode': 'monitor_only_guidance',
 'asset_loading': 'embedded_python_constants',
 'parquet_required': False,
 'artifact_source_path': 'models\\ca_safe_band_mvp_c_line\\safe_band_artifact.json',
 'schema_source_path': 'deploy\\ca_safe_band_mvp_c_line\\schema.json',
 'support_source_path': 'deploy\\ca_safe_band_mvp_c_line\\support.json',
 'future_data_used_for_algorithm_update': False}
